### ISSUE TITLE
Issues with view on Logseq 0.5.6

### ISSUE THREAD

**Issue by sawhney17** [sethyuan/logseq-plugin-doc#1]
![Screen Shot 2021-12-29 at 5 03 01 PM](https://user-images.githubusercontent.com/80150109/147665141-db657cd9-f97a-4a07-b969-e30fc6f44e62.png)
While in the view for doc mode, the bullet lines aren't going away fully in the latest version of logseq. Issue is stemming from the latest feature for clicking the lines to collapse and expand bullets.

**Comment by sethyuan** [comment]
So 0.5.6 is released? I’ll try to adapt it.

**Comment by sethyuan** [comment]
@sawhney17 Compatibility for 0.5.6 is added and a new version is released, please give it a try.

**Comment by sawhney17** [comment]
Looks good now.
