### ISSUE TITLE
How do I change the shortcut key of the plugin

### ISSUE THREAD

**Issue by Aaronjwork** [sethyuan/logseq-plugin-doc#12]
`shift` + `cmd` + `d` conflicts with my  other app's shortcut keys
so, how  I can change the shortcut key of the plugin?

**Comment by sethyuan** [comment]
I released a new version making this shortcut a user setting. You can use it to change the key binding. You need to restart Logseq once you make the changes.

**Comment by Aaronjwork** [comment]
thanks for the reply! I've succeeded in modifying the key binding.
