### ISSUE TITLE
[feature request] options to display tags on/off  - use full width on/off - add custom css

### ISSUE THREAD

**Issue by cannibalox** [sethyuan/logseq-plugin-doc#13]
hey, thank you the the very useful plugin !
Would you consider adding these settings 
 - show/hide tags - currently all tags seem to be hidden with
  ```
  .kef-doc #main-content-container .tag {
      display: none !omportant;
  }
  ```
   - use the full width (or follow logseq's current mode)

  - add custom css rules (I mean adding specific css rules for doc export, on top of the custom.css), this could solve the 2 issues mentioned above

**Comment by sethyuan** [comment]
Glad you like it.

- Regarding full width, it is a bug introduced by new versions of Logseq, the plugin is supposed to work by exporting whatever you see in screen the way they are. I fixed it in the newest version.
- Custom CSS is possible by just overriding in `custom.css`. Say you want the tags be shown:
  ```css
  .kef-doc #main-content-container .tag {
    display: inline-block !important;
  }
  ```
