### ISSUE TITLE
View Mode and Code Blocks

### ISSUE THREAD

**Issue by solariz** [sethyuan/logseq-plugin-doc#15]
Unfortunately if I have enabled the read ony view mode I cant select / copy content from Code blocks anymore.

**Comment by sethyuan** [comment]
You mean you can't select a block as a whole? Because I can select and copy text while in the view mode. If so, that's the intended behavior.

**Comment by sethyuan** [comment]
I'll investigate.

**Comment by sethyuan** [comment]
Fixed it, now you can select, copy or even edit code blocks in the document view.

**Comment by solariz** [comment]
Thank you, can confirm - fixed.
