### ISSUE TITLE
Modification to print bullet symbol when printing the exported html?

### ISSUE THREAD

**Issue by nhan000** [sethyuan/logseq-plugin-doc#16]
this is how my note looks like in the exported html file
![image](https://user-images.githubusercontent.com/85216095/167339604-76dc036c-5828-48c5-8299-6746c855ffe2.png)

This is the printed pdf file (using `Ctrl P` on Google Chrome)
![image](https://user-images.githubusercontent.com/85216095/167339686-5eaa4159-8ee0-4dfb-9c87-70a462c89b91.png)

The bullet point ![image](https://user-images.githubusercontent.com/85216095/167339816-ea8304dd-6313-4991-b943-f400c3b7739e.png) is visible in the exported html file but not in the printed pdf file.

The indentation helps a lot in recognizing the hierarchy. But having a bullet point ![image](https://user-images.githubusercontent.com/85216095/167339816-ea8304dd-6313-4991-b943-f400c3b7739e.png) would help a bit more in recognizing the indentation level. Don't know if you could make it happen somehow?

**Comment by sethyuan** [comment]
Try if this print option of Chrome helps:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/3410293/167346118-04700024-3348-480b-b824-9fe6fd55f2ac.png">

**Comment by nhan000** [comment]
works for me too. Thanks so much!
