### ISSUE TITLE
Blocks jump in Dev theme 

### ISSUE THREAD

**Issue by nhan000** [sethyuan/logseq-plugin-doc#17]
I have a colon `:` between 2 blocks
![image](https://user-images.githubusercontent.com/85216095/168912189-833bdafa-4fdc-4616-bcdf-ae3090600644.png)

When the document view is turned on
![image](https://user-images.githubusercontent.com/85216095/168912239-4204b14d-1411-4607-b684-049b49e20aac.png)

This doesn't happen with Logseq Default Theme

**Comment by sethyuan** [comment]
It must be a CSS rule conflict. The plugin cannot ensure 100% compatibility with all themes, you need to debug it and write CSS to workaround your specific case.

**Comment by nhan000** [comment]
Thank you!

**Comment by nhan000** [comment]
Interestingly with the latest Logseq 0.7.4 the line is broken in the Default Theme too.

![image](https://user-images.githubusercontent.com/85216095/173475007-6f975c79-2349-4092-af3f-e7ac8718a525.png)

Maybe because of this https://github.com/logseq/logseq/pull/5630?

**Comment by nhan000** [comment]
pinging @sethyuan
here's the default document view of Logseq, the line is continuous around the colon `:`
<img width="719" alt="image" src="https://user-images.githubusercontent.com/85216095/174955704-aed716c4-9acd-4dd0-b4a0-d771af137834.png">

**Comment by sethyuan** [comment]
I did some test simulating your case, it looked fine in both the default theme and the theme I use.

![image](https://user-images.githubusercontent.com/3410293/174975235-631202ac-a030-43d4-9802-89639e9ab45c.png)

![image](https://user-images.githubusercontent.com/3410293/174975280-48f851dc-dd87-4968-bc28-abad9ca4e857.png)

I think you need to check your environment, see what themes/plugins/custom CSS you may have that causes this. If you know CSS, you can also use the console to help debug where is wrong.

**Comment by nhan000** [comment]
I don't know what happened but I just checked that page after the latest update and it's fixed. Thanks a lot!

**Comment by sethyuan** [comment]
Curious, I don't remember doing anything that relates. 😅
