### ISSUE TITLE
Did this plugin change it's behavior?

### ISSUE THREAD

**Issue by alxlg** [sethyuan/logseq-plugin-doc#19]
Hi,
if I'm not mistaken this plugin did two things differently before:
1. you were still able to edit blocks, collapse them etc in document mode
2. hide the bullets but keep the indentation in document mode

Am I wrong? Or maybe it was another plugin? Anyway I'm looking for that UX, any tips?

**Comment by sethyuan** [comment]
These 2 are not what the plugin do, I can not help you.
