### ISSUE TITLE
希望固定视图按钮位置

### ISSUE THREAD

**Issue by AdachiQ** [sethyuan/logseq-plugin-doc#2]
目前在点击文档视图按钮后，会向右弹出导出按钮，将视图按钮顶向左侧，若要切换回普通视图需要移动鼠标才能点击，不方便。

希望改成视图按钮不动，或增加快捷键，方便来回切换视图。

**Comment by sethyuan** [comment]
嗯，我可以尝试将导出按钮放在视图按钮的左侧，等我空了调整一下看看效果。感谢反馈！

**Comment by sethyuan** [comment]
@AdachiQ 已更换两个按钮的位置，发布了新版本。

**Comment by AdachiQ** [comment]
> @AdachiQ 已更换两个按钮的位置，发布了新版本。

灰常感谢！
