### ISSUE TITLE
[featur request] Enhance Block IDs in HTML to full fledged Logseq links (optional)

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-doc#20]
The HTML source contains block ids for tags and named pages.
When hovering the browser (Chrome) recognizes the link but does not complete a useful clickable URL.

Files printed to PDF from the browser, look nice but contain no remaining link references

It is possible to either
1. enrich the html to get full fledged Logseq links of the form logseq://graph/my-pkm?block-id=62cd38e0-5071-4bb0-8531-4a3c00012345 for tags?
2. add a javascript to enhance the links in the browser to achieve this.

Options:
* Limit to links inside of the export (useful for Tocs, Security)

Actually the full fledged Logseq Export does some parts this, but the boilerplate is overkill for just one document.
I like your HTML to easily render to PDF.

This is just a suggestion. I need to dive deeper to find out if there is a chance to add it myself.

**Comment by sethyuan** [comment]
Good idea, I'll make researches on this.

**Comment by sethyuan** [comment]
@acsr I released a new version with `logseq://` links support, can you verify if this is what you wanted?

Also, there is a plugin option if you want to show the "Linked References", it had a bug preventing the "Linked References" section to be shown, which I also fixed, so please have a try.

**Comment by acsr** [comment]
@sethyuan **Great work, thanks a lot,** 

- #tag links and [[page]] links work like a charm. 
- Links to Block References like ((62d4087f-2bdb-4206-9e6a-844c3412345)) work!
- Display "Linked References" options is now also working well. 
    - Not sure if true: I seemed I needed one restart of Logseq for fully recognizing changes of the Display "Linked References" option during runtime. After that no restart was required to swap the setting.

I think you can close this feature request,
