### ISSUE TITLE
【功能请求】

### ISSUE THREAD

**Issue by lion-no-back** [sethyuan/logseq-plugin-doc#21]
如果导出的html文件中的代码块可以保持一键复制(如logseq中的效果)及每个块的缩放(折叠)
能很好达到在logseq中展示效果，这个插件对导出功能在细节上的把控才能称的上日臻完善，现在的导出效果也很不错，如果继续优化，相信会受更多人喜爱，很喜欢这款插件  
![1](https://user-images.githubusercontent.com/100990301/178766909-1f2bb065-eba8-49aa-bb08-1d3e366c5950.png)

**Comment by sethyuan** [comment]
我能问一下你是怎么使用doc这个插件的呢？你会拿导出的HTML做什么？

doc的HTML导出我是设计用来通过Google Chrome转换成PDF的，这样得到的PDF效果最好。这个场景是不需要在HTML上有交互的。另外doc导出的HTML是依赖本地资源的，是不能直接分享给其他人的。我觉得如果你需要带有交互的完整HTML导出可以直接使用Logseq本身自带的导出功能。

**Comment by lion-no-back** [comment]
logseq我用来记录解决问题的方案和专业笔记等。

而关于解决问题的方案，我会先在logseq上写好后，然后发到自己的QQ频道里，将解决问题的方案，分享给大家，最初这个过程是通过doc加Opera导出为PDF来解决的(Opera浏览器有自带导出PDF的功能且不分页，可以试试)，但后面遇到的问题是gif没法很好显示还有视频没法夹杂在里面，只有图文并茂貌似还不够，于是我就想到了将html离线，看看效果能不能保存下来，之后通过doc加扩展SingleFile来导出离线html，这样的话关于gif和视频就能很好夹杂在文档中，效果基本可以达到在本地logseq上的效果，这是目前我能找到最好的导出方案这个是demo
[卸载哪些事.zip](https://github.com/sethyuan/logseq-plugin-doc/files/9120293/default.zip)

关于logseq自带的导出HTML功能没能达到这样的要求，因为它导出了大概排版但图片视频资源显示不全，需要手动编辑，没有那么方便快捷，如果是这样，我其实可以直接用markdown进行写作，然后上传公众号，但是这样下来过程比较繁琐，没有导出快和便捷，毕竟用markdown写作，哪怕利用公众号图片上传，有些图片还得上传图床(本地存档)，总之，我也用过，但说实话，最后觉得doc加SingleFile能很好达到我现在的基本期许

之所以提出功能增强这个需求，是站在我这边实用的立场，我认为笔记最为主要的是给自己看，但如果能多一个“借阅”功能就更加完美了，我后期探究的就是将logseq上的一些文章能很好转化为微信公众排版并发布，最后，谢谢你开发的这款插件，提供了我很大的帮助

**Comment by sethyuan** [comment]
了解。关于HTML上的交互功能，我需要有时间的时候再做下调研，图片的内嵌应该也是可以实现的。

**Comment by lion-no-back** [comment]
额嗯，非常期待

**Comment by sethyuan** [comment]
我昨天尝试了一下，确实没有办法保留Logseq的功能，诸如折叠、插件的运行等都是保留不下来的。我想你也许可以换个方法试试，比如为每个课件建一个graph，分享时直接把整个graph分享出去，学生拿到后直接打开graph即可。以上想法供参考。

**Comment by lion-no-back** [comment]
关于折叠，这个的话我已经想到了解决办法，当文章过长时，可以分成几篇来书写，最后来个合集，这个是示例，可以瞅瞅
[IDEA下载及安装.zip](https://github.com/sethyuan/logseq-plugin-doc/files/9129344/IDEA.zip)

关于插件的运行等其实也不需要记录，关于Logseq交互我认为目前doc加SingleFile搭配就可以很好离线导出，且效果已经快要趋于源文件，还算不错，只是有些细节需要优化，如导出时，可以有个目录，目录下的每个章节是个锚链接，方便跳转，还有就是
一些功能因为SingleFile无法实现，所以就哪怕doc实现也没有办法，但我相信这些问题的解决可以交给时间，现在的效果也很不错，只是期待更好的效果

**Comment by lion-no-back** [comment]
刚用过，非常棒，不过我发现这个生成的目录样式稍显呆板

这是我使用vscode书写的markdown的目录样式
![1](https://user-images.githubusercontent.com/100990301/179470472-6faaf108-ce87-42aa-8ace-f3d94126ae3e.png)


这是logseq里的目录样式
![2](https://user-images.githubusercontent.com/100990301/179470537-7aca39a8-0fd6-455d-8031-d1bd2b9874ad.png)

这是导出时的目录样式
![image](https://user-images.githubusercontent.com/100990301/179470620-9879f0c3-1508-4204-9363-6058a49be00b.png)

这里如果优化下，体验是否会更好，可能取决于个人，不过我认为这里可以多一个选择，当然，最为重要的是开发者有没有时间来开发和维护

**Comment by lion-no-back** [comment]
谢谢解答与优化，非常喜欢你所开发的插件，非常棒

**Comment by sethyuan** [comment]
OK，那这个ticket我就先关掉了。另外关于TOC的外观，我不是UI设计师，如果你有好的TOC样式可供参考也可以发给我。
