### ISSUE TITLE
Add a document style #.ul-nested to allow for deep nested unordered lists without markup going wild

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-doc#23]
The #.ul works already great and the #.ol and #.ol-nested from the https://github.com/sethyuan/logseq-plugin-ol plugin as well.

A similar #.ul-nested would help to simplify the markup of deeply nested lists by adding it just to the top level.

Since it is not directly related to the other plugin, I post it here.

**Comment by sethyuan** [comment]
Implemented. Can you try the new version?

**Comment by acsr** [comment]
Thx! The .ul-nested style works for printing as expected. Saves tons of now obsolete work. See other comment if there is any relation to the flow issue described here https://github.com/sethyuan/logseq-plugin-doc/issues/22#issuecomment-1193121772

**Comment by sethyuan** [comment]
I found the issue, it's not related to `#.ul-nested`, it's due to the implementation of back to TOC arrow, I fixed that too.
