### ISSUE TITLE
export is not working

### ISSUE THREAD

**Issue by cnut1648** [sethyuan/logseq-plugin-doc#24]
Hi, thank you for making this plugin. It has been really helpful viewing my pages.

I have a question about export. I am using logseq latest version (version 0.7.9). When I click the export button it doesn't do anything, no pop-up windows. I am using manjaro, in case os will make something different.
What do you think the issue might be? Thanks!

**Comment by sethyuan** [comment]
An error may occurred during the export. Is it just one specific page you have problem with, or no page is working for you at all? It could help if you can turn on the developer console via `cmd + opt + i` or `ctrl + alt + i` and upload an screenshot of the red error here.

**Comment by cnut1648** [comment]
Thanks! I think I found the issue. Seems that export only works on the page level instead of the block level. I was trying to export a block (and its subblocks). Exporting the whole page works fine on my end. When exporting the block it says
![image](https://user-images.githubusercontent.com/37067883/182503280-8b97fed9-1567-4b66-8c64-c40c96979f11.png)
Is it the expected behavior (i.e. the export only works on the page level)? If so I will close the issue.
Thanks!

**Comment by sethyuan** [comment]
Thanks for the screenshot, it is a bug in the plugin. I've fixed it and released a new version. Can you give it a try and see if it works for you.

**Comment by cnut1648** [comment]
Thanks @sethyuan! It works perfectly
