### ISSUE TITLE
Disable intra-graph links

### ISSUE THREAD

**Issue by MrGung** [sethyuan/logseq-plugin-doc#26]
I'd like to give my exported page to others and since they don't have access to my graph, I'd like to be able to disable the links to other pages of my graph.

**Comment by sethyuan** [comment]
The links are local links, the person with the shared file won't be able to open your graph , because they don't have it.

**Comment by MrGung** [comment]
I understand that. I would like these "links" to not be clickable at all. I would like to spare others the time of trying to open a link that wouldn't work anyhow.

**Comment by sethyuan** [comment]
Got it. How do you propose the interaction be? The links generation is actually requested by another user. I can add a plugin option to disable the generation of links to the graph, what do you think?

**Comment by sethyuan** [comment]
I implemented the option, please check the newest version.

**Comment by MrGung** [comment]
Nice. Thanks a lot!

**Comment by sethyuan** [comment]
Welcome!
