### ISSUE TITLE
导出时，主题样式为logseq默认样式而非选择样式

### ISSUE THREAD

**Issue by lion-no-back** [sethyuan/logseq-plugin-doc#27]
因为用的主题一直都是[yoyurec](https://github.com/yoyurec)大佬开发的主题，非常美观大气，然后前段时间导出是可以带着主题样式一起导出，也就是在logseq上是什么样式就导出什么样式，后来因为插件不断优化，这个功能就变糟糕了，为此我向[yoyurec](https://github.com/yoyurec)大佬反映过，然后他向您提出请求你合并后，其效果也没有回到之前，想问下，这个功能可以有嘛，非常喜欢导出时保留在logseq上所选择的主题样式，目前情况如下

logseq上
![001](https://user-images.githubusercontent.com/100990301/187613819-275f354d-61f7-4039-9704-bbd9a1f2dafe.png)
导出时
![002](https://user-images.githubusercontent.com/100990301/187613833-75025de1-309b-43e1-89a6-aec9d1b236e7.png)

一直很喜欢你的插件，很棒，[yoyurec](https://github.com/yoyurec)大佬的主题我也很喜欢，都想要保留

**Comment by sethyuan** [comment]
我刚稍微看了一下，应该是因为它不是一个普通的theme，而是采用了插件的特殊形式制作的主题，所以资源加载方式不同，用了Logseq内部协议，导致插件在导出后加载不到CSS资源。我想想解决办法。

**Comment by sethyuan** [comment]
更新了一个版本，增加了一个配置，`pluginsDir`，你参照提示设置一下应该就可以支持这种复杂主题的导出了。

**Comment by lion-no-back** [comment]
非常棒，解决了，真的非常棒，谢谢分享
