### ISSUE TITLE
不兼容 logseq 0.8.9

### ISSUE THREAD

**Issue by sstiger1230** [sethyuan/logseq-plugin-doc#29]
原先使用正常，非常完美，

但是升级到 logseq 0.8.9后，导出的html文件出现问题，浏览器中无法显示图片，而且页面显示不全。

**Comment by sethyuan** [comment]
已经调整了，解决了导出的HTML无法滚动的问题。
你说的无法显示图片我没能重现。
另外目前还有一个页面标题的样式问题，这个是由Logseq输出了非法HTML导致的，我已经给Logseq报了bug了。

**Comment by sstiger1230** [comment]
导出的html文件，图片地址是src="file://D/logseq__colon/Logseq/assets/image_1665969697150_0.png"
实际的地址应该是："file://D:/Logseq/assets/image_1665969697150_0.png"

**Comment by sethyuan** [comment]
收到，看来Logseq在Windows上又做了些骚操作。我现下没有Windows环境，等我后面看看。

**Comment by sethyuan** [comment]
兼容了Windows上图片的问题，可以尝试下新版本。 @sstiger1230

**Comment by sstiger1230** [comment]
多谢，解决的太迅速了！
