### ISSUE TITLE
Bullet lists not rendering on latest version

### ISSUE THREAD

**Issue by sawhney17** [sethyuan/logseq-plugin-doc#3]
On the latest version of logseq, tagging ul to the list does not make it render as a bullet
![Screen Shot 2021-12-30 at 4 46 18 PM](https://user-images.githubusercontent.com/80150109/147753174-956bde7b-74ef-4eb9-9bfe-7e1770921c7f.png)
![Screen Shot 2021-12-30 at 4 46 27 PM](https://user-images.githubusercontent.com/80150109/147753191-0d760b9d-ffc2-4f26-9b5c-ffea68b474bf.png)

**Comment by sethyuan** [comment]
😂, I didn’t notice. I don’t have my laptop right now, I’ll look into it tomorrow.

**Comment by sethyuan** [comment]
Fixed in the new version, please give it try.
