### ISSUE TITLE
can support close doc view export ?

### ISSUE THREAD

**Issue by feng1o** [sethyuan/logseq-plugin-doc#30]
doc view mod has no indents，exported html is not clearly to read in some case.

can suport export with close doc view mode, and keep style as origin ?

**Comment by sethyuan** [comment]
I'm guessing that you want this option:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/3410293/196642594-84a92636-13ad-4f13-87d4-25d1f4a152f7.png">
