### ISSUE TITLE
能否保留列表竖线

### ISSUE THREAD

**Issue by fanglypro** [sethyuan/logseq-plugin-doc#31]
原始内容：

![image](https://user-images.githubusercontent.com/57083732/198590134-3af0ef2c-a103-4b7f-988e-c3af61231080.png)

预览结果：

![image](https://user-images.githubusercontent.com/57083732/198590088-0907ecfb-82de-45a9-8558-5a44a1df50c6.png)

可以看到没有了列表竖线，在缩进比较多时不利于查看，希望有选项能够保留列表竖线

**Comment by sethyuan** [comment]
不好意思回复晚了，最近在做一款新插件。这个我有空看看。

**Comment by sethyuan** [comment]
@fanglypro  已经调了。
