### ISSUE TITLE
0.9.4版本，导出的html无法滚动，但缩小显示比例能看到下面还有内容

### ISSUE THREAD

**Issue by tchobough** [sethyuan/logseq-plugin-doc#35]
如题，尝试切换多个主题都不行，原生主题也是
![image](https://user-images.githubusercontent.com/109688174/236438313-1086d7ff-529c-46a1-80fe-5fa0ae402b40.png)

**Comment by sethyuan** [comment]
我这边测试是好的，会不会是你的custom.css里有什么样式和插件有冲突？

**Comment by sethyuan** [comment]
那么应该是你安装的某个插件，你先尝试disable所有的插件试试看，再一个一个开启排查一下。

**Comment by tchobough** [comment]
今天又不能导出，这回试出来了，是和 logseq-awesome-ui（https://github.com/yoyurec/logseq-awesome-ui）冲突，打开 Awesome UI，导出结果就没有浏览器滚动条了。
附上我的 Awesome UI 设置（应该是默认设置，没有更改过的印象
![Snipaste_2023-05-15_20-41-10](https://github.com/sethyuan/logseq-plugin-doc/assets/109688174/7a0c6e0b-aee2-4d80-ae3e-f4c2329ccf0e)

**Comment by sethyuan** [comment]
Awesome UI对Logseq的DOM结构做了较大改动，会导致很多问题，我这边也兼容不过来。建议还是不要同时使用吧。

**Comment by tchobough** [comment]
OK，明白了
