### ISSUE TITLE
导出的主题样式与logseq选择样式不一致

### ISSUE THREAD

**Issue by wxcatv** [sethyuan/logseq-plugin-doc#36]
主题：Dev theme
主题样式：dark
pluginsDir已正确填写。
导出html背景为白色，字为浅灰色，基本无法阅读。
试了其他主题，在主题样式为dark时，导出正常。
请检查下。

**Comment by sethyuan** [comment]
还是避免使用dark模式的主题吧，因为暗色背景的导出PDF的时候特别难看。
