### ISSUE TITLE
about exporting

### ISSUE THREAD

**Issue by xkun24h** [sethyuan/logseq-plugin-doc#37]
When exporting HTML, the Draw graph was not exported. Can Draw be supported for export?

**Comment by sethyuan** [comment]
What do you mean by Draw graph? Is it a plugin output?

**Comment by sethyuan** [comment]
I suppose you mean the excalidraw canvas when one types `/Draw`. I released a new version to add compat with it, newer Logseq versions broke the previous support. It's exported as an image now.
