### ISSUE TITLE
Any chance for an option to keep bullets in doc view?

### ISSUE THREAD

**Issue by jpjpjp** [sethyuan/logseq-plugin-doc#38]
This plugin is the best I've found for exporting documents to a printable format.   Sometimes it would be nice to keep the bullets (or at least the indenting of sub-bullets)

**Comment by sethyuan** [comment]
There is a plugin setting `unindentLevel` which is defaulted to 999, you can adjust it to 0 to leave all indentations and bullets.

**Comment by jpjpjp** [comment]
Thanks.  Works like a charm!
