### ISSUE TITLE
Show Linked Reference

### ISSUE THREAD

**Issue by cloudrflight** [sethyuan/logseq-plugin-doc#4]
Linked Reference disappeared in "print-view"
It will be better to see that

**Comment by sethyuan** [comment]
Actually, I'm hiding it intentionally to have a clean document view. However, I understand that some users may want it to be displayed. I implemented a plugin config `showReferences` that you can enable if you want this behavior. I put details in the README file.

**Comment by cloudrflight** [comment]
Thanks , I'll try it later

**Comment by cloudrflight** [comment]
very helpful to me!
