### ISSUE TITLE
DOC视图中，在logseq中折叠块不能显示出来

### ISSUE THREAD

**Issue by Hyc152** [sethyuan/logseq-plugin-doc#40]
![image](https://github.com/sethyuan/logseq-plugin-doc/assets/53823339/22c77147-f438-49e5-8a29-654eb24f559d)
上图是DOC视图，下图是logseq视图
<img width="440" alt="1702051348681" src="https://github.com/sethyuan/logseq-plugin-doc/assets/53823339/34a87f35-391d-4d63-99bb-aaca36918d57">
输出的html文件也不能显示被折叠的块

**Comment by sethyuan** [comment]
这是受Logseq所限，折叠的部分是不会被渲染出来的。
