### ISSUE TITLE
加了# 的标签好像不会显示

### ISSUE THREAD

**Issue by leon900415** [sethyuan/logseq-plugin-doc#5]
<img width="857" alt="CleanShot 2022-01-19 at 10 01 14@2x" src="https://user-images.githubusercontent.com/31237333/150049532-6f8653ac-0bbe-4270-92b3-0660cbde1625.png">
<img width="783" alt="CleanShot 2022-01-19 at 10 01 42@2x" src="https://user-images.githubusercontent.com/31237333/150049566-7f530d68-1613-4cff-8124-86d906f7f30e.png">

**Comment by sethyuan** [comment]
这是刻意设计的行为。因为一般标签是用来作为一种元数据存在的，不算正文的一部分。

我觉得你这里可以用页面引用（[[中间件]] 这种）替换tags，这样不仅可以更符合语意，也能正常作为正文显示出来。

**Comment by leon900415** [comment]
好的 ,  有道理呀.谢谢回复
