### ISSUE TITLE
equations not getting exported properly when exported to HTML

### ISSUE THREAD

**Issue by AvijeetPrasad** [sethyuan/logseq-plugin-doc#7]
When the doc is being exported to HTML, the text for equation is not getting rendered properly.

For example, the text $m_ee^2c$ is being rendered as shown in the attached screenshot. You can see that is first shows the equation in correct form, but then it is followed by the equation text again.

![Screenshot 2022-01-24 at 21 02 20](https://user-images.githubusercontent.com/45669486/150855978-d30aeaf6-651b-4ddc-9a50-001beabab442.jpg)

**Comment by sethyuan** [comment]
Sorry for the inconvenience! However I was unable to reproduce it with the expression you gave. What version of Logseq and the plugin are you using? Can you test it again with the newest version of both? Also, can you try with all the themes disabled?

**Comment by AvijeetPrasad** [comment]
Hi, Thanks for checking this issue. I am currently on `0.5.9+nightly.20220121` of Logseq and version `v1.2.2` of the Doc View Exporter plugin.

I checked again with the default theme but the problem still persists in Safari browser but works fine in Google Chrome.

For a test file with the following content
```
- The theory of relativity connects mass and energy as follows
	- $$e=mc^2$$
```
I got the following results in Safari and Chrome.
![Chrome: Screenshot 2022-01-25 at 11 51 10](https://user-images.githubusercontent.com/45669486/150963525-f30fb2b0-ffe2-45e2-8f04-194fa0e5db3c.jpg)
![Safari: Screenshot 2022-01-25 at 11 51 44](https://user-images.githubusercontent.com/45669486/150963549-57b32dfc-b3a6-4eed-8251-e5a9fd363e51.jpg)

As you can see, the equation is rendered properly in Chrome but not in Safari. So, it could be a browser related issue as well.

**Comment by sethyuan** [comment]
I used Safari to test again, still nothing. It was properly rendered. My Safari version is 15.2. Could it be due to some changes in the nightly version? Can you try 0.5.9?

**Comment by AvijeetPrasad** [comment]
Thanks for checking that. I am also on Safari 15.2. Let me wait till the next Logseq release and then update you back.
