### ISSUE TITLE
Option to only remove dashes from the top-level blocks

### ISSUE THREAD

**Issue by stefanstr** [sethyuan/logseq-plugin-doc#8]
Thank you for this wonderful plugin. I'm using it a lot!

I would like to ask for an extra setting: the ability to remove list marking only from the top-level notes on the page, and keep it on sub-blocks. This is the way I usually export text as I don't nest headings. It would save me from writing `#ul` a lot before exports. :)

**Comment by sethyuan** [comment]
I implemented it, the setting goes by the name of `unindentLevel`, you can read about it in README.

**Comment by stefanstr** [comment]
Awesome, thank you so much! unindentLevel=1 is what I needed.

A small suggestion: perhaps the settings file could contain the default settings instead of being empty when you first install the plugin to make tweaking it easier?
