### ISSUE TITLE
增加导出为pdf功能

### ISSUE THREAD

**Issue by supery-chen** [sethyuan/logseq-plugin-doc#9]
如题

**Comment by sethyuan** [comment]
目前我没有想到直接导出PDF的好方法，但是我做这个插件也是为了导出PDF的。我是这样用的，导出html后用Chrome浏览器打开，再通过Chrome打印成PDF。效果非常好，你也可以试试。

**Comment by supery-chen** [comment]
我目前也是通过这个方式😂

Seth Yuan ***@***.***> 于2022年2月12日周六 11:13写道：
